/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "ApplicationCode.h"
#include "Scheduler.h"

int main(void)
{
	Application_Init();

	uint32_t eventsToRUN;


    /* Loop forever */
	for(;;){
		eventsToRUN = getScheduledEvents();

	if (eventsToRUN & SCHEDULER_TOGGE_ZERO){
		Toggel_Green();
	}

	if(eventsToRUN & SCHEDULER_DELAY){
		Delay(MAGNIFY_DELAY);
	}
	}

}
